# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19gjERFm5zNwKalXakA_xYy7hQ-a7M4La

# A chat bot program
"""

# Importing the library
from nltk.chat.util import Chat, reflections

pairs = [
         ['my name is (.*)', ['hi, %1']],
         ['how are you?', ["I'm good, and you?", "I'm great, and you?"]],
         ['(.*)is fun', ['indeed, %1 is fun']],
         ['(.*)loves(.*) and (.*)', ['yes, %1does love %2 and %3']]
         ]

chat = Chat(pairs, reflections)
chat.converse()

